### ISSUE TITLE
Feature Request: Edit Nicknames

### ISSUE THREAD

**Issue by rreveley** [Wolfsblvt/BlossomsPokemonGoManager#105] opened 2016-08-08 18:56 UTC
If we could edit nicknames in the Manager UI that would be super awesome. Thanks for the great tool.

**Comment by Wolfsblvt** [comment] 2016-08-08 19:12
Duplicate of #47.
It will include simple nicknames, and much more!
Just read it up. Closed here.

**Closed as completed by Wolfsblvt** 2016-08-08 19:12 UTC
Labels: duplicate
