### ISSUE TITLE
Forget order after action

### ISSUE THREAD

**Issue by brunoarocha** [Wolfsblvt/BlossomsPokemonGoManager#196] opened 2016-08-11 13:35 UTC
The order and the sort must remain the same after action (transfer, evolve, etc.).
This helps when you're doing actions to all your pokemons but not in bulk.

**Comment by Wolfsblvt** [comment] 2016-08-11 15:52
Duplicate of #43, and will be done with #65.

**Closed as completed by Wolfsblvt** 2016-08-11 15:52 UTC
Labels: bug, duplicate
