### ISSUE TITLE
Renaming with "%iv_rating%" will replace by "XX"

### ISSUE THREAD

**Issue by leoli-dev** [Wolfsblvt/BlossomsPokemonGoManager#455] opened 2016-10-06 00:14 UTC
<img width="887" alt="2016-10-06 2 09 40" src="https://cloud.githubusercontent.com/assets/1598600/19136157/7299dbee-8b6a-11e6-891e-dfc8faefbe39.png">

New arrival bug after upgrading to v0.1.3

**Comment by Wolfsblvt** [comment] 2016-10-06 00:18
Yeah, duplicate of #446.
Is already fixed in develop.

**Closed as completed by Wolfsblvt** 2016-10-06 00:18 UTC
Labels: bug, duplicate
