### ISSUE TITLE
%iv_rating% is not worked in v0.13

### ISSUE THREAD

**Issue by hkguy80** [Wolfsblvt/BlossomsPokemonGoManager#464] opened 2016-10-07 17:42 UTC
The rename of %iv_rating% is not worked in v0.13. It will show XX instead of the actual value.

**Comment by Wolfsblvt** [comment] 2016-10-07 17:59
That's why I already releases v0.1.4 :P 

Duplicate of #446.

**Closed as completed by Wolfsblvt** 2016-10-07 17:59 UTC
Labels: bug, duplicate
