### ISSUE TITLE
Mulitple DPS values for Move 2

### ISSUE THREAD

**Issue by Lacero** [Wolfsblvt/BlossomsPokemonGoManager#117] opened 2016-08-09 04:32 UTC
I see this in almost every Move 2 that I have multiple pokemon with. No errors with Move 1.

![image](https://cloud.githubusercontent.com/assets/20910359/17504609/7e328a16-5dc8-11e6-934b-fdc32edc7388.png)

**Comment by Ljaysoft** [comment] 2016-08-09 13:38
The difference in dps is intended,  different dps is caused by the Same Type Attack Bonus, but there was indeed a problem with the dps calculation, it's fixed in the next build. See #52

**Closed as completed by Ljaysoft** 2016-08-09 13:38 UTC
Labels: bug, duplicate
