### ISSUE TITLE
BUG: Pattern %Move_Type_2% returns the same type than %Move_Type_1%

### ISSUE THREAD

**Issue by ksanchezm** [Wolfsblvt/BlossomsPokemonGoManager#439] opened 2016-10-02 13:56 UTC

**Comment by Wolfsblvt** [comment] 2016-10-02 14:40
Yeah. Fixed in develop already and will be part of the next version.
Duplicate of #418.

**Closed as completed by Wolfsblvt** 2016-10-02 14:40 UTC
Labels: bug, duplicate

**Comment by ksanchezm** [comment] 2016-10-02 17:35
Awesome! Thanks for all the effort in this app.I honestly can't imagine
myself without it.
