### ISSUE TITLE
won't start

### ISSUE THREAD

**Issue by newbiE247** [Wolfsblvt/BlossomsPokemonGoManager#397] opened 2016-09-17 15:24 UTC
i followed the guide, installed newest java, downloaded lates version and did the google auth key thing. but after i entered the google key nothing happens. it just won't start and there is no process in the taskmanager. any ideas?

ps: i'm on windows 10

**Comment by Wolfsblvt** [comment] 2016-09-17 17:52
Confirmed, others have this problems too. Have to check what causes the issue.

**Comment by petridish2** [comment] 2016-09-17 17:55
Hey, Woldsblvt.  petri from discord chat here.  Thanks for looking into it!

**Comment by newbiE247** [comment] 2016-09-17 18:04
hi wolfsblvt, thanks for your time and the fast response.

**Comment by petridish2** [comment] 2016-09-17 20:19
newbiE247, are you using a VPN?

**Comment by newbiE247** [comment] 2016-09-18 00:33
no, not using VPN. i don't have any special setup. just standard DSL and standard windows 10.

**Comment by petridish2** [comment] 2016-09-18 00:36
Must have been a coincidence then that it started working for me after I disconnected my VPN.  I probably tried opening it about 50-60 times prior to that, then after my second or third try after disconnecting, it decided to work for some reason.  I'm afraid to close it now!

**Comment by newbiE247** [comment] 2016-09-18 00:46
haha, yea i've read in the comments, that someone got it to work by starting it multiple times. i tried it, but no luck for me so far.

**Comment by Wolfsblvt** [comment] 2016-09-18 21:18
For Note, error message like:

```
[22:59:48]: com.pokegoapi.exceptions.AsyncPokemonGoException: Unknown exception occurred. 
[22:59:48]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:46)
[22:59:48]:     at com.pokegoapi.main.RequestHandler.sendServerRequests(RequestHandler.java:155)
[22:59:48]:     at com.pokegoapi.api.PokemonGo.fireRequestBlockTwo(PokemonGo.java:230)
[22:59:48]:     at com.pokegoapi.api.PokemonGo.initialize(PokemonGo.java:170)
[22:59:48]:     at com.pokegoapi.api.PokemonGo.login(PokemonGo.java:164)
[22:59:48]:     at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:218)
[22:59:48]:     at me.corriekay.pokegoutil.data.managers.AccountController.logOff(AccountController.java:342)
[22:59:48]:     at me.corriekay.pokegoutil.windows.MenuBar.logout(MenuBar.java:139)
[22:59:48]:     at me.corriekay.pokegoutil.windows.MenuBar.lambda$new$52(MenuBar.java:44)
[22:59:48]:     at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
[22:59:48]:     at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
[22:59:48]:     at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
[22:59:49]:     at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
[22:59:49]:     at javax.swing.AbstractButton.doClick(Unknown Source)
[22:59:49]:     at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
[22:59:49]:     at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
[22:59:49]:     at java.awt.Component.processMouseEvent(Unknown Source)
[22:59:49]:     at javax.swing.JComponent.processMouseEvent(Unknown Source)
[22:59:49]:     at java.awt.Component.processEvent(Unknown Source)
[22:59:49]:     at java.awt.Container.processEvent(Unknown Source)
[22:59:49]:     at java.awt.Component.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Container.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Component.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[22:59:49]:     at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[22:59:49]:     at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.Container.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Window.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.Component.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[22:59:49]:     at java.awt.EventQueue.access$500(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$3.run(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$3.run(Unknown Source)
[22:59:49]:     at java.security.AccessController.doPrivileged(Native Method)
[22:59:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[22:59:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$4.run(Unknown Source)
[22:59:49]:     at java.awt.EventQueue$4.run(Unknown Source)
[22:59:49]:     at java.security.AccessController.doPrivileged(Native Method)
[22:59:49]:     at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[22:59:49]:     at java.awt.EventQueue.dispatchEvent(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[22:59:49]:     at java.awt.EventDispatchThread.run(Unknown Source)
[22:59:49]: Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[22:59:49]:     at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
[22:59:49]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:465)
[22:59:49]:     at rx.observables.BlockingObservable.first(BlockingObservable.java:168)
[22:59:49]:     at com.pokegoapi.util.AsyncHelper.toBlocking(AsyncHelper.java:38)
[22:59:49]:     ... 46 more
[22:59:49]: Caused by: java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[22:59:49]:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:109)
[22:59:49]:     at com.pokegoapi.main.RequestHandler$1.get(RequestHandler.java:86)
[22:59:49]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:74)
[22:59:49]:     at rx.internal.operators.OnSubscribeToObservableFuture$ToObservableFuture.call(OnSubscribeToObservableFuture.java:43)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
[22:59:49]:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[22:59:49]:     at rx.Observable.subscribe(Observable.java:9957)
[22:59:49]:     at rx.Observable.subscribe(Observable.java:9924)
[22:59:49]:     at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:445)
[22:59:49]:     ... 48 more
[22:59:49]: Caused by: com.google.protobuf.InvalidProtocolBufferException: Contents of buffer are null
[22:59:49]:     at com.pokegoapi.main.ServerRequest.getData(ServerRequest.java:80)
[22:59:49]:     at com.pokegoapi.main.RequestHandler.run(RequestHandler.java:296)
[22:59:49]:     at java.lang.Thread.run(Unknown Source)
```

**Comment by Wolfsblvt** [comment] 2016-09-19 14:37
Started a try to fix it. Need help testing it. Whoever knows git a bit, can you test out this PR and see if the problem is fixed?

**Closed as completed** 2016-09-20 21:26 UTC
Labels: bug
