### ISSUE TITLE
Save last used pattern in Rename action

### ISSUE THREAD

**Issue by magicjj** [Wolfsblvt/BlossomsPokemonGoManager#351] opened 2016-09-02 00:30 UTC
Currently I have to retype my naming pattern each time I use the rename, but I use it often with the same pattern after a big hunt. Would be great if it saved my input in a settings file.

**Comment by Wolfsblvt** [comment] 2016-09-02 00:41
Already in the works: #325, and is a duplicate of #295.

**Closed as completed by Wolfsblvt** 2016-09-02 00:41 UTC
Labels: duplicate, enhancement
