### ISSUE TITLE
Blossoms not working using PTC login

### ISSUE THREAD

**Issue by adronl** [Wolfsblvt/BlossomsPokemonGoManager#498] opened 2016-11-23 23:38 UTC
So immediately following event update no blossoms for double xp.  Tried updating java uninstalled blossoms and reinstalled still no love. Help please

**Comment by Wolfsblvt** [comment] 2016-11-23 23:41
I guess you caught Ditto, didn't you?

Then it's a duplicate of #489.

**Closed as completed by Wolfsblvt** 2016-11-23 23:41 UTC
Labels: bug, duplicate
