### ISSUE TITLE
Renaming Error

### ISSUE THREAD

**Issue by Spedwards** [Wolfsblvt/BlossomsPokemonGoManager#252] opened 2016-08-15 11:04 UTC
Tried renaming a handful of my Pokemon using the patterns and got an identical error on each of them.

```
[08/15 21:00:02]: Doing Rename 1 of 13
[08/15 21:00:02]: Renaming Ekans failed! Code: ERROR_INVALID_NICKNAME; Nick: %iv_stam% / %iv_att% / %iv_def%
```

Either the instructions for the name aren't clear/incorrect, are something is going wrong in the code.

**Comment by underko** [comment] 2016-08-15 13:17
I think it's caused by a nickname length limit of 12 characters.

**Comment by Wolfsblvt** [comment] 2016-08-15 13:26
Yep, the limit is 12 characters.
Will be fixed in future updates, the name will be cut off then.

**Closed as completed by Wolfsblvt** 2016-08-15 13:26 UTC
Labels: bug, duplicate
