### ISSUE TITLE
Actions taken ingame will interrupt BPGM; Maybe Add a Note

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#383] opened 2016-09-16 00:20 UTC
Maybe add a note/disclaimer/red text/context menu popup that actions taken ingame while BPGM is working will interrupt the manager. Low priority, but I know I forget. 

IE: mass renaming while getting a Pokestop will error out BGPM. Same with catching a pokemon. And evolving.

**Comment by Wolfsblvt** [comment] 2016-09-16 08:39
Have done this several time and I have never seen an error there.
Can you provide the error message and/or post a screenshot?

I will test this soon again, but yesterday I caught some Pokémon while bulk transferring and it worked.

**Comment by ISeeTanamon** [comment] 2016-09-16 18:49
Confirmed. 

Bulk rename, go in game and swipe a pokestop. You'll see BPGM actually just not continue, no error. Sometimes you get the whole "server not responding message" from time to time, but havent seen that one yet.

**Comment by Wolfsblvt** [comment] 2016-09-16 19:02
So what should the tool do if you do something like that?
It's very likely that the API is just blocking more requests than x per second or such.

**Comment by ISeeTanamon** [comment] 2016-09-17 00:10
Hm. Theres no real way to know unless the manager is blocked (if the manager knows its blocked from continuing, a break point could be made and a message saying "action interrupted, try action again in a few seconds without acting in PokemonGo" kind of thing.

Otherwise, what the manager does right, is it stops. It doesnt override or continue (which is good, because if we're catching a Pokemon and we're sending Evolve commands during the catching process... lol).

**Comment by Wolfsblvt** [comment] 2016-09-30 00:21
Okay, change of plan.
We will just add a simple statement for the user stating that using actions ingame my cause bulk operations in BPGM to cancel.

Should be enough.

**Comment by boomschtick** [comment] 2016-10-06 16:13
I would not say that this is true in all occasions.  Just yesterday, I did a very large bulk evolve (over 100).  I was able to catch Pokemon while the evolution was going on and it did not cause the evolution's to stop.  Maybe it's just Poke stops.  I have not tried that.

**Comment by Wolfsblvt** [comment] 2016-10-06 21:44
Yeah, I did this quite some times too. Seems to be working most of the times, but not always.

**Comment by FernandoTBarros** [comment] 2017-04-09 22:35
I can confirm this not happens anymore. I did a bulk evolve in BPGM while doing evolve in game. Maybe it's happening in older versions of API. If this keep happening after the next release send a message and we will open this issue.

**Closed as completed by FernandoTBarros** 2017-04-09 22:35 UTC
Labels: wontfix / invalid
