### ISSUE TITLE
Renaming with %iv_rating% is broken in 0.1.3

### ISSUE THREAD

**Issue by boomschtick** [Wolfsblvt/BlossomsPokemonGoManager#457] opened 2016-10-06 15:31 UTC
In every case that I have tried, using %iv_rating% results in a XX in the Nickname.  No matter what the actual IV's are.

Using %name_4% %iv_rating% %hp% results in:

Pidg XX 56

**Comment by pat15312** [comment] 2016-10-06 15:55
I can confirm that this is also happening for me.

**Comment by Wolfsblvt** [comment] 2016-10-06 21:42
Yep. Duplicate of #446.

**Closed as completed by Wolfsblvt** 2016-10-06 21:42 UTC
Labels: bug, duplicate
