### ISSUE TITLE
[Bug] Renaming Pattern

### ISSUE THREAD

**Issue by AbcentMineDead** [Wolfsblvt/BlossomsPokemonGoManager#453] opened 2016-10-05 21:43 UTC
%iv_rating% pattern is only outputting "XX" as if every Pokemon I renamed were 100% IV.

**Comment by Wolfsblvt** [comment] 2016-10-05 21:47
Duplicate of #446.
Fixed already on develop.

**Closed as completed by Wolfsblvt** 2016-10-05 21:47 UTC
Labels: bug, duplicate
