### ISSUE TITLE
Feature request: export to .csv

### ISSUE THREAD

**Issue by tdshimo** [Wolfsblvt/BlossomsPokemonGoManager#403] opened 2016-09-18 22:56 UTC
Would be nice to have a quick button to export values. Thanks for this project, though!

**Comment by Wolfsblvt** [comment] 2016-09-18 22:57
Duplicate of #63.
Will be possible (:

**Closed as completed by Wolfsblvt** 2016-09-18 22:57 UTC
Labels: duplicate, enhancement

**Comment by tdshimo** [comment] 2016-09-18 23:34
My fault - I searched, but not well enough! Thanks!
