### ISSUE TITLE
"Unfortunately, your login has failed.."

### ISSUE THREAD

**Issue by MeatB4g** [Wolfsblvt/BlossomsPokemonGoManager#102] opened 2016-08-08 16:37 UTC
I'm receiving the error: "Unfortunately, your login has failed. Press OK to try again."

I'm receiving and using google login authentication code properly.

Using the email associated with the Go account login.

Any tips?

**Comment by Wolfsblvt** [comment] 2016-08-08 16:57
The login in your App on your phone is working though?
Seems like some more have that issue. We have to check.

**Comment by Wolfsblvt** [comment] 2016-08-08 17:02
As mentioned in #103 the Login for PTC is not working either.

**Comment by Ljaysoft** [comment] 2016-08-08 17:34
From what I can tell, deleting the json config file fixes the problem for me, but that's on my development branch atm, so it's either a "fixed" or "will be fixed soon". I can't replicate the problem at least.

**Comment by thomashaentjens** [comment] 2016-08-08 17:48
I"m using the .jar file as i'm at work write now but i'll try it out with the source tonight home.

As well I tried with the game logged in and out and have the same issue.

**Comment by Wolfsblvt** [comment] 2016-08-08 17:49
Guess @Ljaysoft meant you should delete the `config.json` file that lies in the same folder as the jar does.

**Comment by thomashaentjens** [comment] 2016-08-08 17:54
I tried it first and nothing changes, is there a chance that Niantic cut down the access as they did for PokeAdvisor for exemple ?

**Comment by Ljaysoft** [comment] 2016-08-08 18:09
I wouldn't think so, because there are many people for who it works. we're still investigating the problem.

**Comment by thomashaentjens** [comment] 2016-08-09 07:17
Hi there, well I just tried it back this morning ( well i'm in france ) and everything work perfectly. I don't know if you guys did something but thank you anyway. Really great job to all of you this rock !!

**Comment by Wolfsblvt** [comment] 2016-08-09 09:08
So is this issue resolved? @MeatB4g?

**Comment by thomashaentjens** [comment] 2016-08-09 09:23
To me it is 👍  i'll try to look trough the code to see if i can help you guys with some of my coding skills well I could finish the translation in french for the UI and the attack name if you like.

**Comment by GuillaumeCisco** [comment] 2016-08-09 14:13
Same thing for me, it doesn't work.
I'm in France.
I have a gmail account and use an android phone, tried to login on a ubuntu machine.
My coworker has a gmail account too and use an iphone, he executed the jar on a mac  and it works for him.
Hope it helps ;)

**Comment by Wolfsblvt** [comment] 2016-08-09 14:24
Have you tried deleting the config.json file?

**Comment by GuillaumeCisco** [comment] 2016-08-09 14:29
Yes, It does not work too.
I try to build the develop branch, but I'm not familiar with maven, and don't know how to install the com.pokegoapi with intellij idea.

**Comment by Wolfsblvt** [comment] 2016-08-09 14:39
With IntelliJ, just import the project as existing source, then select Maven as project.
Maven will install dependenciesautomatically.

**Comment by GuillaumeCisco** [comment] 2016-08-09 14:52
Ok... I must be a noob with those tools. I imported the project as existing source, selected maven project, next, next, next...
Build Menu -> Make project. Still like no dependencies have been downloaded (Intellij IDEA 15).
I have 100 errors that look like:

```
Error:(3, 25) java: package com.pokegoapi.api does not exist
```

**Comment by Wolfsblvt** [comment] 2016-08-09 14:56
Try adding a Run configuration  (top right of the IDE), choose "Application" and selectBlossomsPokemonGoManager as start class

**Comment by weblue** [comment] 2016-08-09 14:57
@GuillaumeCisco right click the pom.xml hover over the maven menu and click sync/scan

**Comment by GuillaumeCisco** [comment] 2016-08-09 15:21
Thank you for your help guys.
But I still cannot download the maven dependencies... I don't know what I'm missing.
Just redownloaded the latest version if Intelij Idea (2016.2.1).
Opened the project by selecting the pom.xml
Have the JDK 1.8 selected for the project.
Clicked on `Reimport All Maven Projects` or `Reimport` or `Generate Sources and Update Folders`.
Still the same error when I try to `make` the project...

All the dependencies are red underlined.
Sorry for this inconvenience guys. I think I'll wait a development version jar built for testing and answering this issue :)
I'll try the current release version on a windows 10 machine tonight.

**Comment by Wolfsblvt** [comment] 2016-08-09 21:06
Can someone for whom it does not work tell me if there is a backslash in the token that you copied?

I have created a fix attempt on develop which will be released with the next version. Maybe it fixes all there.
Please test the next version and then tell me if it works.

**Comment by Wolfsblvt** [comment] 2016-08-10 02:25
Okay guys, a new version is released!
It may fix this bug, but I need a clear response if it does.
Can someone of you test it and give a short answer?

The new release can be found here: [v0.1.2-alpha.1](https://github.com/Blossomforth/BlossomsPokemonGoManager/releases/tag/v0.1.2-alpha.1)

**Comment by iDuzDis** [comment] 2016-08-10 05:26
hey guys, i cant seem to get it to work for the life of me, i have tried everything, from restarting pc to downloading new java etc, deleting the config.json, downloading the new version. 

it takes me to the google auth and gives me a new code every time but once i paste it into the box and click ok it loads for a bit then fails

**Comment by Wolfsblvt** [comment] 2016-08-10 05:31
A few questions there.
1. Are you absolutely sure that it is the same Google Account where you get the token for than the one ingame?
2. In the folder where the jar is, is there any log file? Can you paste it's content?
3. What's the exact error or error message that you see? If there is no error, have you checked that the window isn't hidden behind some other window?

**Comment by iDuzDis** [comment] 2016-08-10 05:38
1. yep same acc and everything
2. in the folder that you get with the download, it has the blossomspogomanager jar file, the config.json, console, license, readme, runonunixlikesystems.sh and runonwindows. no log file
3. "unfortunately, your login has failed. pressok to try again

**Comment by Wolfsblvt** [comment] 2016-08-10 05:43
The console file. Open it with a text editor and paste the contents here. That's the log :P

**Comment by iDuzDis** [comment] 2016-08-10 05:44
ahhh my bad xD 

[08/10 06:38:54]: Could not fetch config item 'login.PTCUsername'! Fallback to default: null
[08/10 06:38:54]: Could not fetch config item 'login.PTCPassword'! Fallback to default: null
[08/10 06:38:55]: Could not fetch config item 'login.GoogleAuthToken'! Fallback to default: null
[08/10 06:39:19]: Could not fetch config item 'login.PTCUsername'! Fallback to default: null
[08/10 06:39:19]: Could not fetch config item 'login.PTCPassword'! Fallback to default: null
[08/10 06:39:19]: Could not fetch config item 'login.SaveAuth'! Fallback to default: false

**Comment by Wolfsblvt** [comment] 2016-08-10 05:52
No more messages? o.O
Seems like the exception gets swallowed.

Can you try this jar file to debug the problem a bit more?
It should have a more detailed message as the Popup. Post that here.
Also there should be more stuff in the console.log file with that jar. Please paste everything here too. (If it contains a token, change some letters, otherwise people have your login :D )

_EDIT: Removed file_

**Comment by iDuzDis** [comment] 2016-08-10 05:58
[08/10 06:54:02]: Could not fetch config item 'login.PTCUsername'! Fallback to default: null
[08/10 06:54:02]: Could not fetch config item 'login.PTCPassword'! Fallback to default: null
[08/10 06:54:02]: Could not fetch config item 'login.SaveAuth'! Fallback to default: false
[08/10 06:54:06]: Could not fetch config item 'login.GoogleAuthToken'! Fallback to default: null
[08/10 06:54:30]: Exception at Google Auth Stuff
[08/10 06:54:30]: com.pokegoapi.exceptions.RemoteServerException: Network Request failed to fetch tokenId
[08/10 06:54:30]:   at com.pokegoapi.auth.GoogleUserCredentialProvider.login(GoogleUserCredentialProvider.java:196)
[08/10 06:54:30]:   at me.corriekay.pokegoutil.controllers.AccountController.logOn(AccountController.java:165)
[08/10 06:54:30]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:19)
[08/10 06:54:30]: Caused by: java.net.SocketTimeoutException: connect timed out
[08/10 06:54:30]:   at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
[08/10 06:54:30]:   at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
[08/10 06:54:30]:   at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
[08/10 06:54:30]:   at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
[08/10 06:54:30]:   at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
[08/10 06:54:30]:   at java.net.PlainSocketImpl.connect(Unknown Source)
[08/10 06:54:30]:   at java.net.SocksSocketImpl.connect(Unknown Source)
[08/10 06:54:30]:   at java.net.Socket.connect(Unknown Source)
[08/10 06:54:30]:   at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
[08/10 06:54:30]:   at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:187)
[08/10 06:54:30]:   at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
[08/10 06:54:30]:   at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
[08/10 06:54:30]:   at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
[08/10 06:54:30]:   at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
[08/10 06:54:30]:   at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
[08/10 06:54:30]:   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[08/10 06:54:30]:   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[08/10 06:54:30]:   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 06:54:30]:   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 06:54:30]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[08/10 06:54:30]:   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
[08/10 06:54:30]:   at okhttp3.RealCall.execute(RealCall.java:60)
[08/10 06:54:30]:   at com.pokegoapi.auth.GoogleUserCredentialProvider.login(GoogleUserCredentialProvider.java:194)
[08/10 06:54:30]:   ... 2 more

and the the pop up box has "reason: network request failed to fetch tokenid"

**Comment by Wolfsblvt** [comment] 2016-08-10 06:06
Okay, that exception helps much more. Are you on a work environment? Could it be that some network ports are blocked?

Seems like the query to the server timed out without a response in time.

**Comment by iDuzDis** [comment] 2016-08-10 06:11
im actually at home, not sure what could be blocking it though, it might not be the same thing but when i used pokeadvisor the google auth worked for that

**Comment by iDuzDis** [comment] 2016-08-10 06:15
ok i got it to work, the one thing should have to mind first was the firewall xD turn it off and now it works, thanks for all the help! :D

**Comment by GuillaumeCisco** [comment] 2016-08-10 08:06
Hello folks.
Just tested the latest release a home on a windows 10 machine and it worked !
Just tried the latest release this morning at work on an ubuntu machine and it doesn't work too :/
I'll try with the debug zip you provided and connecting my work laptop to my 4G phone network. :)

**Comment by GuillaumeCisco** [comment] 2016-08-10 08:15
Just tried at work with my 4G network and the same thing happened :/
Using the debug version I get this error message:

```
Unfortunately, your login has failed. Reason: Network Request failed to fetch tokenId
Press OK to try again.
```

console.log is:

```
[08/10 10:10:58]: Could not fetch config item 'login.PTCUsername'! Fallback to default: null
[08/10 10:10:58]: Could not fetch config item 'login.PTCPassword'! Fallback to default: null
[08/10 10:10:58]: Could not fetch config item 'login.SaveAuth'! Fallback to default: false
[08/10 10:10:59]: Could not fetch config item 'login.GoogleAuthToken'! Fallback to default: null
[08/10 10:11:16]: Exception at Google Auth Stuff
[08/10 10:11:16]: com.pokegoapi.exceptions.RemoteServerException: Network Request failed to fetch tokenId
[08/10 10:11:16]:   at com.pokegoapi.auth.GoogleUserCredentialProvider.login(GoogleUserCredentialProvider.java:196)
[08/10 10:11:16]:   at me.corriekay.pokegoutil.controllers.AccountController.logOn(AccountController.java:165)
[08/10 10:11:16]:   at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:19)
[08/10 10:11:16]: Caused by: java.net.ConnectException: Failed to connect to www.googleapis.com/[censured]:443
[08/10 10:11:16]:   at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189)
[08/10 10:11:16]:   at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
[08/10 10:11:16]:   at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
[08/10 10:11:16]:   at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
[08/10 10:11:16]:   at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
[08/10 10:11:16]:   at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
[08/10 10:11:16]:   at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[08/10 10:11:16]:   at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[08/10 10:11:16]:   at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 10:11:16]:   at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[08/10 10:11:16]:   at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[08/10 10:11:16]:   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
[08/10 10:11:16]:   at okhttp3.RealCall.execute(RealCall.java:60)
[08/10 10:11:16]:   at com.pokegoapi.auth.GoogleUserCredentialProvider.login(GoogleUserCredentialProvider.java:194)
[08/10 10:11:16]:   ... 2 more
```

**Comment by Wolfsblvt** [comment] 2016-08-10 09:25
@GuillaumeCisco As @iDuzDis mentioned, can you check if the firewall on your working computer is the problem?
Often work computers have stricter firewalls that block certain requests that go out on certain ports, which makes this tool useless then.

**Comment by GuillaumeCisco** [comment] 2016-08-10 09:58
@Wolfsblvt , I've tried with the 4g network of my mobile phone with tethering with no more luck.
My cowroker uses a Mac under the company network and it works.

Really don't know why it doesn't work on my ubuntu machine.

**Comment by Wolfsblvt** [comment] 2016-08-10 13:29
That's why I was asking for blocked ports and firewall, @GuillaumeCisco. That could be the problem.

**Comment by GuillaumeCisco** [comment] 2016-08-10 14:57
I'm sorry, I don't understand @Wolfsblvt . Using the 4G network of my phone in tethering, I don't rely on the possible firewall of my company. Am I missing something?
I have no blocked ports on my machine.

**Comment by Wolfsblvt** [comment] 2016-08-10 15:00
The firewall on your computer, not the network one.
Try deactivating it.

**Comment by GuillaumeCisco** [comment] 2016-08-10 15:32
The firewall of my xubuntu distribution is disabled by default.
 Just checked it.

**Comment by Wolfsblvt** [comment] 2016-08-10 15:49
It's just strange ._.
For most people the latest update fixed the problems with login. For most others the problem was related to blocked connections and stuff.

I am at my wit's end.

**Comment by thomashaentjens** [comment] 2016-08-10 17:58
Well the problem might be any connection regulation system for sure it does work at home where my connection is fully open and not at work where the connection is via VPN so it must be VPN, Firewall, and stuff that bloc the connection at certain point.

Also i don't have windows at home but at work and osX at home

**Comment by Wolfsblvt** [comment] 2016-08-10 18:03
Yeah, seems so.
Will close that issue though. Don't think it's really tool-related or that we can find a solution there.

**Closed as completed by Wolfsblvt** 2016-08-10 18:03 UTC
Labels: bug, waiting for more

**Comment by GuillaumeCisco** [comment] 2016-08-11 07:36
Thank you guys for your time :)
I really appreciate that, it's a wonderful project, I use it at home, and... work at work ;)

**Comment by GuillaumeCisco** [comment] 2017-02-27 10:31
Hello guys, just got a new exception with the last release regarding login.
I now have an exception related to trustAnchors parameter.

Here is the console.log file:
```
[11:20:04]: Error: RemoteServerException
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[11:28:15]: com.pokegoapi.exceptions.RemoteServerException: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[11:28:15]: 	at com.pokegoapi.auth.GoogleAutoCredentialProvider.login(GoogleAutoCredentialProvider.java:78)
[11:28:15]: 	at com.pokegoapi.auth.GoogleAutoCredentialProvider.<init>(GoogleAutoCredentialProvider.java:49)
[11:28:15]: 	at me.corriekay.pokegoutil.data.managers.AccountController.logOn(AccountController.java:298)
[11:28:15]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.openOldGui(BlossomsPoGoManager.java:118)
[11:28:15]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.start(BlossomsPoGoManager.java:70)
[11:28:15]: 	at me.corriekay.pokegoutil.BlossomsPoGoManager.main(BlossomsPoGoManager.java:34)
[11:28:15]: Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[11:28:15]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1410)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[11:28:15]: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:241)
[11:28:15]: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
[11:28:15]: 	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
[11:28:15]: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
[11:28:15]: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
[11:28:15]: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
[11:28:15]: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
[11:28:15]: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[11:28:15]: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[11:28:15]: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[11:28:15]: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[11:28:15]: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[11:28:15]: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
[11:28:15]: 	at okhttp3.RealCall.execute(RealCall.java:60)
[11:28:15]: 	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLogin(Gpsoauth.java:86)
[11:28:15]: 	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:103)
[11:28:15]: 	at svarzee.gps.gpsoauth.Gpsoauth.performMasterLoginForToken(Gpsoauth.java:90)
[11:28:15]: 	at com.pokegoapi.auth.GoogleAutoCredentialProvider.login(GoogleAutoCredentialProvider.java:73)
[11:28:15]: 	... 5 more
[11:28:15]: Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[11:28:15]: 	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90)
[11:28:15]: 	at sun.security.validator.Validator.getInstance(Validator.java:179)
[11:28:15]: 	at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
[11:28:15]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
[11:28:15]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
[11:28:15]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[11:28:15]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491)
[11:28:15]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
[11:28:15]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[11:28:15]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[11:28:15]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[11:28:15]: 	... 30 more
[11:28:15]: Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
[11:28:15]: 	at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
[11:28:15]: 	at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
[11:28:15]: 	at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
[11:28:15]: 	at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88)
[11:28:15]: 	... 42 more
```

I tried using an APP password based authentication.
My gmail account includes two steps verification.
I'm at work.

**Comment by Wolfsblvt** [comment] 2017-02-28 13:57
At work is nearly always a problem.
Do you use a VPN there? Proxies? Firewalls? That will not work.

And for new issues, please open new issues :P
