### ISSUE TITLE
Pogo Manager stopped working after obtaining a Ditto

### ISSUE THREAD

**Issue by GTekes** [Wolfsblvt/BlossomsPokemonGoManager#501] opened 2016-11-24 00:33 UTC
After I caught a Ditto, I wasn't able to open the Pogo Manager v0.1.4. Here is the dump:

[19:45:22]: Stats: Lvl 28 Mystic player.
[19:45:22]: Pokédex - Types Caught: 138, Total Pokémon Caught: 3999, Total Current Pokémon: 342 (+9 Eggs)
[19:45:22]: Current version: v0.1.4
[19:45:22]: Latest version from server: v0.1.4
[19:45:23]: Highest Duel Ability: Snorlax with Lick and Hyper Beam has 21209394375
[19:45:23]: Highest Gym Offense: Dragonite with Dragon Breath and Hyper Beam has 467062.5
[19:45:23]: Highest Gym Defense: Lapras with Ice Shard and Ice Beam has 9490026563
[19:45:23]: Load saved locations from file.
[19:45:23]: java.lang.NullPointerException
[19:45:23]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:89)
[19:45:23]: 	at me.corriekay.pokegoutil.utils.pokemon.PokemonCalculationUtils.dpsForMove(PokemonCalculationUtils.java:75)
[19:45:23]: 	at me.corriekay.pokegoutil.data.enums.PokeColumn$13.get(PokeColumn.java:106)
[19:45:23]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.lambda$updateTableData$0(PokemonTableModel.java:48)
[19:45:23]: 	at java.util.ArrayList.forEach(Unknown Source)
[19:45:23]: 	at java.util.Collections$SynchronizedCollection.forEach(Unknown Source)
[19:45:23]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTableModel.updateTableData(PokemonTableModel.java:43)
[19:45:23]: 	at me.corriekay.pokegoutil.utils.windows.PokemonTable.constructNewTableModel(PokemonTable.java:108)
[19:45:23]: 	at me.corriekay.pokegoutil.windows.PokemonTab.refreshList(PokemonTab.java:1040)
[19:45:23]: 	at me.corriekay.pokegoutil.windows.PokemonTab.lambda$new$10(PokemonTab.java:248)
[19:45:23]: 	at me.corriekay.pokegoutil.utils.helpers.LDocumentListener$1.lambda$changedUpdate$0(LDocumentListener.java:58)
[19:45:23]: 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
[19:45:23]: 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[19:45:23]: 	at java.awt.EventQueue.access$500(Unknown Source)
[19:45:23]: 	at java.awt.EventQueue$3.run(Unknown Source)
[19:45:23]: 	at java.awt.EventQueue$3.run(Unknown Source)
[19:45:23]: 	at java.security.AccessController.doPrivileged(Native Method)
[19:45:23]: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[19:45:23]: 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[19:45:23]: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[19:45:23]: 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[19:45:23]: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[19:45:23]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[19:45:23]: 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[19:45:23]: 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Wolfsblvt** [comment] 2016-11-24 00:34
Yeah, already fixed and will be released soon.

Duplicate of #489.

**Closed as completed by Wolfsblvt** 2016-11-24 00:34 UTC
Labels: bug, duplicate

**Comment by adr-sit** [comment] 2016-11-24 12:59
I caught a Ditto (transformed from Pidgey) too. Should I not using the program at the moment?

**Comment by Wolfsblvt** [comment] 2016-11-24 13:31
The latest version, **0.1.5** has the problem fixed already. So you can just use that (:
