### ISSUE TITLE
Allow Users to Hide Columns

### ISSUE THREAD

**Issue by ISeeTanamon** [Wolfsblvt/BlossomsPokemonGoManager#384] opened 2016-09-16 00:23 UTC
Love more info. Allow users to maybe hide columns on stuff they dont need (IE, Max Evolved CP, Caught With, Time Caught, etc) so that users can expand and enlarge text (basically granularity select their viewing preferences even more) to their own comfort. Maybe add a View tab, where it states "Unhide All" or maybe in View -> Tabs, list out all the possible tabs so users can go back and forth to enable/disable/see whats available/unavailable.

**Comment by Wolfsblvt** [comment] 2016-09-16 08:41
Yes, will happen with the new UI.
I know it's a bit annoying that it will not work right now, but we can't implement everything in the old GUI, otherwise we won't make progress on the new one. Despite the fact that adding such things to the old UI would be soo much pain. It's really difficult.

Also, close this as a duplicate of #65.

**Closed as completed by Wolfsblvt** 2016-09-16 08:41 UTC
Labels: duplicate, enhancement
