### ISSUE TITLE
Batch Transfer - Calling the new API

### ISSUE THREAD

**Issue by tangrl** [Wolfsblvt/BlossomsPokemonGoManager#525] opened 2016-12-16 17:01 UTC
I just downloaded the latest version (0.1.6) and found that the batch transfer is stilling doing it one by one. Can we call the new API which transfer many Pokemons in one call? It will save us lot of time.

Thanks!

**Comment by tangrl** [comment] 2016-12-19 17:40
I feel this is more than a performance issue. Since Niantic has provided a fast batch-transfer way, if we are still doing the old way by making many calls, will it raise a red flag?

Thanks!

**Comment by Wolfsblvt** [comment] 2016-12-19 20:50
Duplicate of #513.

Sadly I have no control about the new function. It needs to be reversed and then the Java API needs to implement it. Then we can use that.

**Closed as completed by Wolfsblvt** 2016-12-19 20:50 UTC
Labels: bug, duplicate
