### ISSUE TITLE
Respect in-game timers

### ISSUE THREAD

**Issue by XargonWan** [Wolfsblvt/BlossomsPokemonGoManager#267] opened 2016-08-16 10:40 UTC
I think that you should put an option to respect the game timers for evolution, transfers, renames etc so you won't be banned for botting.

EG: with a lucky egg you are able to evolve 70 pokemon circa, with blossom you can evolve a lot more and that can trigger you a permaban cause it is a client strange behavior.

**Comment by ritsu** [comment] 2016-08-16 12:56
It takes roughly 25 seconds per evolve if you're doing it in the official app. Currently, BPGM uses a default 3-12 second delay between evolves. This is user configurable in the current develop branch (look in config.json), so you can set the minimum delay to 25 seconds if you want to mimic official app behavior. 

Might be worth considering 25 seconds as a default setting. Although, fwiw, you can do it slightly faster if you force close and reopen the app during the animation-- it effectively skips the animation and can be faster than 25 seconds if you are on a fast device and fast wifi, and the servers are healthy. I've also been able to evolve on 2 phones at the same time, so there's that.

**Comment by Wolfsblvt** [comment] 2016-08-16 14:22
True. And it is implemented already with #157 (:
Will be included in the next version.

For now, you have to manually configure the timers via the JSON file though if you don't like the default settings.

So this is a duplicate of #220.

**Closed as completed by Wolfsblvt** 2016-08-16 14:22 UTC
Labels: bug, duplicate
