### ISSUE TITLE
Shifted columns will reset to default location after action

### ISSUE THREAD

**Issue by Munkenmo** [Wolfsblvt/BlossomsPokemonGoManager#330] opened 2016-08-25 12:03 UTC
I wanted to shift the "CP Evolved" column to the left (between HP and Max CP columns).  

After any action eg:
- renaming a pokemon
- filtering by pokemon
- transferring
- (etc)

Any column that I shift will reset back to it's default location.

Can there be a setting added to either remember columns shifts permanently, or at least to remember changes for an entire session?

**Comment by Ljaysoft** [comment] 2016-08-25 14:18
The feature was added in the new GUI and will be included in 0.2.0

**Comment by Wolfsblvt** [comment] 2016-08-25 15:51
Yeah, and it's actually a duplicate of issue #65.

**Closed as completed by Wolfsblvt** 2016-08-25 15:51 UTC
Labels: duplicate, enhancement
